### ISSUE TITLE
File missing `molfm-hn/checkpoint_199.pth`

### ISSUE THREAD

**Issue by CiaoHe** [PharMolix/OpenBioMed#21]
The current tutorial is missing the access way of molfm-hn/checkpoint_199.pth.

**Comment by icycookies** [comment]
We have fixed this. The checkpoint of MolFM is `./ckpts/fusion_ckpts/molfm.pth`

Best

**Comment by CiaoHe** [comment]
got it. thx a lot

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Yizhen Luo ***@***.***>
发送时间: Friday, August 18, 2023 1:51:50 PM
收件人: PharMolix/OpenBioMed ***@***.***>
抄送: He Cao ***@***.***>; Author ***@***.***>
主题: Re: [PharMolix/OpenBioMed] File missing `molfm-hn/checkpoint_199.pth` (Issue #21)


We have fixed this. The checkpoint of MolFM is ./ckpts/fusion_ckpts/molfm.pth

Best

―
