### ISSUE TITLE
Links misdirect for `ppi.md`

### ISSUE THREAD

**Issue by CiaoHe** [PharMolix/OpenBioMed#23]
Hi again.
I found the link in https://github.com/PharMolix/OpenBioMed/blob/main/docs/ppi.md#data-preparation misdirected to something called `ProteinDB.zip` but not `SHS27K` dataset. Please have a check. The limited resources in the web I can find just
* https://drive.google.com/drive/folders/1Yb-fdWJ5vTe0ePAGNfrUluzO9tz1lHIF

As required in the https://github.com/PharMolix/OpenBioMed/blob/5114e35e3b9c1dbc673b21636cb8b5b1580dbc97/open_biomed/datasets/ppi_dataset.py#L96 and https://github.com/PharMolix/OpenBioMed/blob/5114e35e3b9c1dbc673b21636cb8b5b1580dbc97/open_biomed/datasets/ppi_dataset.py#L86
Perhaps we need some "interactions.txt" and "sequences.tsv"

**Comment by icycookies** [comment]
check `BioMedGPT/data/downstream tasks/ppi.zip` [here](https://pan.baidu.com/s/1iAMBkuoZnNAylhopP5OgEg?pwd=7a6b#list/path=%2F). `interactions.txt` and `sequences.tsv` are data files processed by us.

Best

**Comment by CiaoHe** [comment]
Great, I've seen the updated files. Thx!
