### ISSUE TITLE
未找到多模态模型checkpoint文件

### ISSUE THREAD

**Issue by quzhi-quer** [PharMolix/OpenBioMed#25]
您好，我在试用您的模型时发现您的checkpoint文件似乎是不同模态分别存储的？我在您给出的百度网盘链接上下载到了LLM的checkpoint但没有找到蛋白的checkpoint，因此没法运行[biomedgpt_inference.ipynb](https://github.com/PharMolix/OpenBioMed/blob/main/examples/biomedgpt_inference.ipynb)这个文件，会找不到OpenBioMed-main/ckpts/protein_ckpts/esm2-3b/config.json。不知道这个文件是在其他什么地方吗？如果当下没有的话未来会开源吗？

**Comment by icycookies** [comment]
模型的checkpoint文件是用同一个文件存储的，但文本模型和蛋白质模型的网络结构设置（与Llama-2-7B和ESM2-3B结构一致）分别存储在`OpenBioMed-main/ckpts/text_ckpts/biomed-llama-7b/config.json`和`OpenBioMed-main/ckpts/protein_ckpts/esm2-3b/config.json`中，请从[此处](https://huggingface.co/PharMolix/BioMedGPT-LM-7B/tree/main)和[此处](https://huggingface.co/facebook/esm2_t36_3B_UR50D/tree/main)下载两个config文件（无需下载模型参数），放置在对应位置即可加载BioMedGPT-10B。

**Comment by HsinChinLi** [comment]
Is there anything to do with path settings?
Even after following the instructions and downloaded all required files, still receive "no such file" error for biomedgpt_10b.pth.
Does this have anything to do with "_name_or_path" settings within the config.json?

**Comment by tszslovewanpu** [comment]
> 模型的checkpoint文件是用同一个文件存储的，但文本模型和蛋白质模型的网络结构设置（与Llama-2-7B和ESM2-3B结构一致）分别存储在`OpenBioMed-main/ckpts/text_ckpts/biomed-llama-7b/config.json`和`OpenBioMed-main/ckpts/protein_ckpts/esm2-3b/config.json`中，请从[此处](https://huggingface.co/PharMolix/BioMedGPT-LM-7B/tree/main)和[此处](https://huggingface.co/facebook/esm2_t36_3B_UR50D/tree/main)下载网络结构和tokenizer的config文件（无需下载模型参数），放置在对应位置即可加载BioMedGPT-10B。
> 
> 具体的config文件可参考我们最新的jupytor notebook。
> 
> 感谢您对BioMedGPT的关注和支持！

感谢！
