### ISSUE TITLE
基于功能生成蛋白质的能力

### ISSUE THREAD

**Issue by LGH1gh** [PharMolix/OpenBioMed#27]
您好，我对你们的工作非常感兴趣。我是做蛋白质设计方向的，但是在[biomedgpt_inference.ipynb](https://github.com/PharMolix/OpenBioMed/blob/main/examples/biomedgpt_inference.ipynb)文件中，只有给定蛋白质生成功能的例子，请问有生成相关的例子可以提供吗，

**Comment by icycookies** [comment]
感谢您对BioMedGPT的关注！目前BioMedGPT仅支持文本生成功能，我们将在未来工作中支持基于文本的蛋白质生成。
