### ISSUE TITLE
十个下游任务是否可用

### ISSUE THREAD

**Issue by hsrr** [PharMolix/OpenBioMed#41]
你好，请问下这里提到的十个下游任务，像那个蛋白质相互作用的预测任务，是否做出来了呢（代码可以跑吗）测试结果咋样呀。

**Comment by icycookies** [comment]
PPI任务的运行请参考[文档](https://github.com/PharMolix/OpenBioMed/blob/main/docs/ppi.md)，实验结果与[论文](https://arxiv.org/abs/2201.11147)一致。我们将在后续更新中给出各个下游任务的完整benchmark :)

**Comment by hsrr** [comment]
好的谢谢
