### ISSUE TITLE
Code and model of MV-Mol

### ISSUE THREAD

**Issue by FZU-LW** [PharMolix/OpenBioMed#70]
Hi, I'd like to know when the code and model of MV-Mol will be released,. Thank you!

**Comment by icycookies** [comment]
Thanks for your interest in our work! We are still revising the codes, datasets, and checkpoints of MV-Mol into Open-BioMed.  For an overview of MV-Mol, please refer to [this repo](https://github.com/icycookies/MV-Mol) (Note: it is a developing branch that we are actively working on).

**Comment by FZU-LW** [comment]
Thx!
